# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: hackathon-next

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: /
    steps:
    - uses: actions/checkout@v3
    - name: Experiment
      run: |
        pwd
        
        ls -R
        pwd
     
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
    - name: Set up cache
      uses: actions/cache@v3
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies 
      run: poetry install --no-interaction --no-root
      
    - name: Activate virtualenv
      working-directory: ${{env.working-directory}}
      run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
    - name: Run tests
      
      run: |
        pytest
